name: Format

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Run black
        run: black alphonse
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Format code using black
          title: Format code.
          body: Format code using black.
          labels: ⚫️ black
          repository: .
          commit_user_name: ryoishin
          commit_user_email: ryoishincoder@gmail.com
          commit_author: ryoishin <ryoishincoder@gmail.com>
